student_name = str("Ali Khan")
student_age = int(16)
student_grade = str("10th")
student_gpa = float(3.8)
print(f"{student_name} is {student_age} years old and currently in {student_grade} grade with a GPA of {student_gpa}.")